### ISSUE TITLE
Account for nodes whose outputs are not requested in the MBDyn model

### ISSUE THREAD

**Issue by zanoni-mbdyn** [zanoni-mbdyn/blendyn#11]
The output of specific nodes can be disabled in MBDyn, for example using the 
```
output, no
```
directive at the end of their definition in the input file. 

Blendyn gathers the information about the nodes present in the model from the .log file, in which no information about their output is given. So it is possible that a node without any output is imported in the Blender scene, causing trouble when the animation is requested. 

Blendyn should be able to recognise that the output of specific nodes has been disabled, and just warn the user without stopping the animation of the other nodes.

**Comment by janga1997** [comment]
@zanoni-mbdyn I think the last point will need a little more study of MBDyn on my part. Let's just keep this open till some days in the Community bonding period, when I should be able to take a crack at this again.
Meanwhile, I will work on the other open issue.

**Comment by janga1997** [comment]
We could implement this pretty easily by parsing the input file, but that feels going backward, as we could potentially parse everything from the input file. I thought we were supposed to parse node/element info from the log file.
If logging the value of the `output` in the log file for every node (along with the currently logged positional/rotational values) in MBDyn doesn't seem like a good idea, I will implement it in Blendyn.

**Comment by zanoni-mbdyn** [comment]
Actually, there is another possibility: we could check upon loading the results from the `.mov` or the `.nc` file if the output of the current node (that we found in the .log file as usual) is present or not. If not, we skip to the next node and warn the user. 

The tricky part is the dealing with the elements connected to the nodes that do not write their output. Obviously, they must be neglected as well.

**Comment by janga1997** [comment]
Right. That should work.
