### ISSUE TITLE
Give full path of currently imported file

### ISSUE THREAD

**Issue by louisgag** [zanoni-mbdyn/blendyn#16]
Currently, the Blendyn interface reports the name of the MBDyn results file which has been imported, but does not give the path. In some cases this can lead to confusion. For example, I run parametric iterations of the same model which always gets created with the same filename but in a different folder. It can be confusing for me to remember which one I have loaded.

I think a simple solution to this would be to have the full path of the imported file show up when the user places the mouse over the short name of the imported file.

**Comment by zanoni-mbdyn** [comment]
I've added the full path of the currently imported output file below the file info (number of nodes, number of time steps, ecc...). 

You can try by checking out the `testing` branch.
