### ISSUE TITLE
Automatic text info widgets/indicators/overlays

### ISSUE THREAD

**Issue by louisgag** [zanoni-mbdyn/blendyn#17]
This feature request may require a lot of work.

When creating a scientific simulation, the interest of the user is quite often in the actual numbers.

In its current state, Blendyn does not provide a simple method to print data from the simulation in text form above the rendered animation. It would be great feature if this were made possible. Perhaps the best approach would be to let the user create an equation from the results. For example, if the user wants to show absolute velocity of a node, they could have the "(X_vel^2+Y_vel^2+Z_vel^2)^(1/2)" info printed for each frame of the animation. Time would obviously also be useful.

Here are some examples from animations I have done in the past, but I always did them using post-processing on the Blender/OtherSoftware rendered animation images:

Here a simple example: https://youtu.be/VG4qZFkcFnU

And a more complex one: http://louisgagnon.com/pressPlot.gif

**Comment by zanoni-mbdyn** [comment]
This is *definetely* not a trivial one :)
