### ISSUE TITLE
Euler angles interpretation

### ISSUE THREAD

**Issue by zanoni-mbdyn** [zanoni-mbdyn/blendyn#40]
@louisgag, I'm opening this in relation to #38 : seems to me that the correct interpretation was actually the previous one, in which the order of the three Euler angles should be *reversed* in Blender, with respect to MBDyn conventions.

Simple test: define a new Empy Axes, rotate it of some amount about its X axis, then of some other amount about the new Y axis, then again of something about the new Z axis. Read the angles in the Item tab and you'll see that the angles differ with respect to those you gave during the individual rotations. Now switch to the 'ZYX' parametrization, redo the same and you'll see that this time the values coincide. 

So it seems that the Blender convention is to store in the Euler angles the three subsequent rotations that bring the object from the global orientation to the local one and not, as usual, the opposite direction. 

I'm reverting back to how things were done before #38, in the new branch `eulerangles`. Can you please test and report? I'm doing the same.

**Comment by louisgag** [comment]
Andrea,
I tried to make the code in the branch eulerangles fail on the angles and couldn't... not sure how I had come to think that it failed before.
Sorry for the confusion!

**Comment by zanoni-mbdyn** [comment]
No problem, glad to hear that it is all okay :) 
Merging.
