### ISSUE TITLE
Type error occured while trying to load .log files to Blendyn interface on Blender

### ISSUE THREAD

**Issue by TranHuuNhatHuy** [zanoni-mbdyn/blendyn#48]
### Describe problem:
An error popped up when I tried to load `.log` file after importing `.mov` file, as shown below:
```python
Python: Traceback (most recent call last):
  	File "/home/tranhuunhathuy/.config/blender/3.1/scripts/addons/blendyn-master/blendyn.py", line 931, in invoke
    	return self.execute(context)
  	File "/home/tranhuunhathuy/.config/blender/3.1/scripts/addons/blendyn-master/blendyn.py", line 866, in execute
    	ret_val, obj_names = parse_log_file(context)
  	File "/home/tranhuunhathuy/.config/blender/3.1/scripts/addons/blendyn-master/baselib.py", line 384, in parse_log_file
    	mbs.num_timesteps = mbs.num_rows/mbs.num_nodes
	TypeError: bpy_struct: item.attr = val: BLENDYN_PG_settings_scene.num_timesteps expected an int type, not float

        location: <unknown location>:-1
```

### Conditions to reproduce:
- Ubuntu 20.04.4
- MBDyn 1.7.3
- Current version of Blendyn
- Blender 3.1.2
- Python 3.8.10
- All dependencies of MBDyn, Blender and Blendyn installed

## Steps to reproduce:
1. Take one input file from [MBDyn examples](https://www.mbdyn.org/?Documentation___Official_Documentation___Examples) and run simulation with MBDyn.
2. On Blendyn interface, import `.mov` output file by clicking `Select results file`.
3. Click `Load .log file`.

## Verified solution:
Force type-cast to int for [mbs.num_timesteps](https://github.com/zanoni-mbdyn/blendyn/blob/master/baselib.py#L384).

**Comment by zanoni-mbdyn** [comment]
Thank you for the feedback. Should be fixed in 38a855b2eeacb27f88ab3e042fd4fe1b5622e959, in branch `bugfix`. Please test and report.
