### ISSUE TITLE
import imp missing from utilslib.py

### ISSUE THREAD

**Issue by DavidFletcherShef** [zanoni-mbdyn/blendyn#57]
Setting up on Mac (MacOS 14.5, Apple Silicon) with Blender 4.1.1 I was getting an error that numpy was not installed, even though other add-ons could detect it without problems. 

I found that adding `import imp` to the top of utilslib.py solved the problem.

**Comment by zanoni-mbdyn** [comment]
Fixed in 316792fc8194f4ada85fdc49f25612761837ea39
